services:
  database:
    image: postgres:15.4
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:24.0.4
    env_file:
      - keycloak.env
    ports:
      - "8080:8080"
      - "8443:8443"
    command: start-dev
    volumes:
      - ./certs:/opt/keycloak/mycerts
      - keycloak-data:/opt

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - database
      - keycloak
    volumes:
      - ./certs:/app/certs

  frontend:
    build:
      context: ./frontend
      args:
        SSL_CRT_FILE: ${SSL_CRT_FILE}
        SSL_KEY_FILE: ${SSL_KEY_FILE}
    env_file:
      - .env
    ports:
      - "80:3000"
      - "443:3000"
    depends_on:
      - database
      - keycloak
      - backend
    volumes:
      - ./certs:/app/certs

volumes:
  database-data:
  keycloak-data: